baseURL = "https://ericmurphy.xyz/"
title = "Eric Murphy"

[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.main]]
    name = "Videos"
    url = "https://www.youtube.com/channel/UC5KDiSAFxrDWhmysBcNqtMA"
    weight = 10

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/ericmurphyxyz"
    weight = 20

  [[menu.main]]
    name = "Contact"
    url = "mailto:eric@ericmurphy.xyz"
    weight = 30
